import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

function formatDateTime(date: Date) {
  return date.toLocaleString("es-CO", {
    timeZone: "UTC",
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function PostEntry({ post }: { post: any }) {
  return (
    <div>
      <span>{post.name}</span>{' '}
      <span className="text-sm text-gray-500">{formatDateTime(post.createdAt)}</span>
    </div>
  );
}

export default function Home() {
  const { data } = api.post.getAll.useQuery();
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-800 to-slate-500">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <SignOutButton />}
          <p className="text-2xl text-white">
            {data
              ? data.map((post) => <PostEntry key={post.id} post={post} />)
              : "..."}
          </p>
        </div>
      </main>
    </>
  );
}
