import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import { RouterOutputs, api } from "~/utils/api";

function formatDateTime(date: Date) {
  return date.toLocaleString("es-CO", {
    timeZone: "UTC",
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

type Post = RouterOutputs["post"]["getAll"][number];

/**
 * Render a list of posts.
 *
 * @param posts The array of posts to render.
 * @return The rendered list of posts.
 */
function PostsList({ posts }: { posts: Post[] }): JSX.Element {
  return (
    <p className="text-2xl text-white">
      {posts.map((post) => (
        <PostEntry key={post.id} post={post} />
      ))}
    </p>
  );
}

/**
 * Renders a post entry.
 *
 * @param post The post object.
 * @returns The rendered post entry.
 */
function PostEntry({ post }: { post: Post }): JSX.Element {
  return (
    <div className="p-2 text-slate-100">
      <div className="font-mono">{post.name}</div>
      <div className="text-sm font-thin text-gray-300">
        {formatDateTime(post.createdAt)}
      </div>
    </div>
  );
}

function UserButtons() {
  const user = useUser();

  return (
    <div className="p-2 text-slate-300">
      {!user.isSignedIn && (
        <div>
          <SignInButton />
        </div>
      )}
      {user.isSignedIn && (
        <div className="flex flex-row gap-2">
          <Image
            src={user.user?.imageUrl}
            width={48}
            height={48}
            alt=""
            className="rounded-full"
          />
          <SignOutButton />
        </div>
      )}
    </div>
  );
}

export default function Home() {
  const { data, isLoading } = api.post.getAll.useQuery();

  if (!data || isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-slate-800 to-slate-500">
        <div className="container m-auto flex h-screen w-full flex-col border-x border-slate-300 md:max-w-3xl">
          <UserButtons />
          <PostsList posts={data} />
        </div>
      </main>
    </>
  );
}
